# Generated by Django 2.0.13 on 2020-03-24 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvfile', '0003_auto_20200324_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='memo',
            field=models.TextField(blank=True),
        ),
    ]
