# Generated by Django 2.0.13 on 2020-03-25 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvfile', '0004_profile_memo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='memo',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='spend',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='spendwon',
        ),
        migrations.AddField(
            model_name='profile',
            name='latitude',
            field=models.CharField(default=11, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='longitude',
            field=models.CharField(default=11, max_length=50),
            preserve_default=False,
        ),
    ]
