# Generated by Django 2.0.13 on 2020-03-27 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mylocations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=5, max_digits=8, verbose_name='Latitude')),
                ('lon', models.DecimalField(decimal_places=5, max_digits=8, verbose_name='Longitude')),
            ],
        ),
    ]
