# Generated by Django 2.0.13 on 2020-03-27 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distsum', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mylocations',
            new_name='Mylocation',
        ),
    ]
