# Generated by Django 2.0.13 on 2020-03-30 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distsum', '0002_auto_20200327_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mylocation',
            name='lat',
            field=models.TextField(verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='mylocation',
            name='lon',
            field=models.TextField(verbose_name='Longitude'),
        ),
    ]
